### PR TITLE
Update Deps and add qt-webkit-kiosk

### PR DESCRIPTION
**Pull request by mobileoverlord**
This PR covers the following
* nerves_system_br to 0.13.3
* toolchain v0.11.0
* fixes elixir 1.5 warnings
* adds vcs metadata
* fixes issue with Nerves.Runtime.KV being unable to access the uboot env

I am having an issue with the application data partition being mounted. Early on across the console, there is an error about the filesystem being too small for a journal. I don't think that its being formatted correctly. Thats the only thing left from my testing.

Booting to Phoenix
Booting to default index page

### CODE REVIEW

**Comment by fhunleth** [comment]
I can help with the app partition error. Add this to the fwup.conf:

```
define-eval(APP_PART_LAST_BLOCK, "${APP_PART_OFFSET} + ${APP_PART_COUNT} - 1")
```
and then add this to the complete task next to the other memsets:
```
# Make sure that the image file is large enough to hold the entire app partition
raw_memset(${APP_PART_LAST_BLOCK}, 1, 0xff)
```

**Comment by fhunleth** [comment]
Super cool, though!

**Comment by mobileoverlord** [comment]
That seems to have buffered out the space properly, but, It is failing to mount the partition with the error `mounting /dev/mmcblk0p4 on /root failed: No such device` I've poked around `/sys/class/block/mmcblk0p4` and the `size` attribute is being reported as `1048560` and the `ro` attribute is `0`

**Comment by fhunleth** [comment]
The size attribute should be 1048576. It feels like there's a math error somewhere or something weird going on. If you pad it out a little more, I'm sure that it will work, but curious as to the 16 block size discrepancy.

**Review by fhunleth — APPROVED** [review]

**Pull request merged**
